In [2]:
import numpy as np
import pandas as pd
from pandas import DataFrame
import matplotlib.pyplot as plt
from IPython.display import display
import random

### Ask User Input ###
def user_guess(guess = None):
    while True:
        guess = input ("Please input a 5 letter word :")
        if type(guess) != str or len(guess) != 5:
            print('Please enter a 5 letter word!!!')
            continue
        else:
            return guess.upper()
## This part generates a random word from the bank ###    
def word_generator():
    bank = ['eagle', 'zebra', 'tiger', 'shark', 'whale', 'lemur', 'ant', 'hippo'
            ,'snail', 'rhino', 'snake', 'taste', 'hello', 'waste', 'paste', 'nymph', 'roate', 'snore', 'stare', 'ocean', 'fuzzy'
           , 'green', 'earth', 'edict', 'graph', 'acute', 'elite', 'basis', 'forum', 'youth', '']
    correct_word = random.choice(bank)
    return correct_word
### Controls the colors ###
def color_changer(value):
    if value == value.upper() and len(value) == 1:
        color = 'green'
    elif len(value) == 2:
        color = 'orange'
    else:
        color = 'black'
    return 'color: %s' % color

## This part of the code checks if the letter is right ###
def letter_checker(guess_index):
    last = []
    for item in guess_index:
        if item[2] == 'YES':
            last.append(item[0])
        elif item[2] == 'EX':
            last.append(item[0] + ' ')
        else:
            last.append(item[0].lower()) 
    return last

## Builds the interface the the user uses ###
## Uses pandas help create table ###
def build_interface(att, guess_arr):
    columns = ['1', '2', '3', '4', '5']
    index = ['Attempt # ' + str(att +1)]
    
    interface = pd.DataFrame(guess_arr).T
    interface.index = index
    interface.columns = columns
    
    
    return interface


############  Actual game! ################
def wordle():
    correct_word = word_generator()
    
    #Turns the random word into an array"
    true_arr = np.array(list(correct_word.upper()))
    true_index = [[item, index, None] for index, item in enumerate(true_arr)]
    num_attempts = 0
    guesss = []
    
    while num_attempts < 6:
        word = user_guess()
        guess_arr = np.array(list(word))
        guess_index = [[item, index, None] for index, item in enumerate(guess_arr)]
        matched = []
        existing = []
        matching = np.where(true_arr == guess_arr)[0]

        for item in matching:
            matched.append(guess_index[item][0])
            guess_index[item][2], true_index[item][2] = 'YES', 'YES'

        rem_guess = [item for item in guess_index if item[2] != 'YES']
        rem_true = [item for item in true_index if item[2] != 'YES']
      
        for i in rem_guess:
            for x in rem_true:
                if i[0] == x[0]:
                    if list(true_arr).count(i[0]) > (matched.count(i[0]) + existing.count(i[0])):
                        existing.append(i[0])
                        i[2], x[2] = 'EX', 'EX'
                    else:
                        continue
        #Redefines color changer
        def color_changer(value):
            if value == value.upper() and len(value) == 1:
                color = 'green'
            elif len(value) == 2:
                color = 'orange'
            else:
                color = 'black'
            return 'color: %s' % color

        last = letter_checker(guess_index)
        
        guess_interface = build_interface(num_attempts, last)
        guesss.append(guess_interface)
        new_interface = pd.concat(guesss)
        
        #Uses color changer
        s = new_interface.style.applymap(color_changer)
        display(s)

        if word.lower() == correct_word:
            print('                                                              ')
            print(f'       Yay! The  Wordle Word Was: {correct_word.upper()} ')
            print('                                                               ')
            print('YOU ARE A GENIUS! UT SHOULD BE PROUD!!!')
            print('HOOK EM :)')
            print("Do you want to play another wordle")
            break
        else:
            num_attempts += 1
            
            if num_attempts == 6:
                print(f'Sorry, Wordle is hard, the correct word was {correct_word.upper()}, its okay...')
                break

if __name__ == '__main__':
    wordle()

Please input a 5 letter word :audio

Please input a 5 letter word :every

Please input a 5 letter word :leans

Please input a 5 letter word :snark

Please input a 5 letter word :snack

Please input a 5 letter word :snake

       Yay! The  Wordle Word Was: SNAKE

YOU ARE A GENIUS! UT SHOULD BE PROUD!!!
HOOK EM :)
Do you want to play another wordle